---
title: "Activity 23"
author: "Amar Dani"
date: "12/05/22"
output: html_notebook
---
```{r}
library(ggplot2)
library(ggthemes)
library(raster)
```

```{r}
kc = shapefile('/Users/sandeep/Downloads/R\ Code/geo_export_938071c2-c2a2-4adf-9dfd-e42bc17487e1.shp')
```
```{r}
kc.data = fortify(kc)
```
```{r}
head(kc.data)
```
```{r}
fountains <- read.csv('/Users/sandeep/Downloads/R\ Code/Fountain.csv')
```

```{r}
ggplot(data=kc.data, aes(x=long, y=lat)) +
  geom_polygon(aes(group=group), fill='#3b3a3a', color='#707070') + coord_quickmap() + 
  geom_point(
    data = fountains, 
    aes(x=Longitude, y=Latitude), 
    fill='#255202',
    color = '#000000',
    shape = 21, 
    size = 3,
    alpha = 0.35
  ) + theme_map() + 
  labs(
    title = "Fountains in Kansas City",
    caption = 'Kansas City Neighborhood Boundaries (2022)'
  ) + theme(
    plot.title = element_text(face = 'bold',size=18),
    plot.caption = element_text(size=8, face='italic',color='grey70', hjust=0)
  )
```
```{r}
minneapolis = shapefile('/Users/sandeep/Downloads/R\ Code/Minneapolis_Communities.shp')
bike_racks <- read.csv('/Users/sandeep/Downloads/R\ Code/bike-racks-umn.csv')
```
```{r}
minneapolis.data = fortify(minneapolis)
head(minneapolis.data)
```
```{r}
ggplot(data=minneapolis.data, aes(x=long, y=lat)) +
  geom_polygon(aes(group=group), fill='#3b3a3a', color='#707070') + coord_quickmap() +
  geom_point(x=44.9749, y=-93.2373, shape = 8, size=2, fill='#fcf919', color='#000000') + theme_map() + 
  geom_point(
    data = bike_racks, 
    aes(x=longitude, y=latitude, fill=Condition),
    shape = 21, 
    size = 2,
    alpha = 0.35
  ) +
  labs(
    title = "Bike Racks in Minneapolis",
    caption = 'Minneapolis Open Data (2022)',
    fill = 'Bike Rack Condition'
  ) + theme(
    plot.title = element_text(face = 'bold',size=18),
    plot.caption = element_text(size=8, face='italic',color='grey70', hjust=0),
    legend.title = element_text(size=8, face = 'bold.italic'),
    legend.position = c(0.95,0.07),
  )
```
```{r}
ggplot(data=minneapolis.data, aes(x=long, y=lat)) +
  geom_polygon(aes(group=group), fill='#3b3a3a', color='#707070') + coord_quickmap() +
  geom_point(x=44.9749, y=-93.2373, shape = 8, size=2, fill='#fcf919', color='#000000') + theme_map() + 
  geom_point(
    data = bike_racks, 
    aes(x=longitude, y=latitude, fill=Condition),
    shape = 21, 
    size = 2,
    alpha = 0.35
  ) +
  labs(
    title = "Bike Racks in Minneapolis",
    subtitle = 'Focused onto the University of Minnesota',
    caption = 'Minneapolis Open Data (2022)',
    fill = 'Bike Rack Condition'
  ) + theme(
    plot.title = element_text(face = 'bold',size=18),
    plot.subtitle = element_text(size=12),
    plot.caption = element_text(size=8, face='italic',color='grey70', hjust=0),
    legend.title = element_text(size=8, face = 'bold.italic'),
    legend.position = c(0.85,0.07),
  )  + coord_cartesian(xlim = c(-93.22,-93.26), ylim = c(44.965,44.985))
```
```{r}
minneapolis_centerline = shapefile('/Users/sandeep/Downloads/R\ Code/PW_Street_Centerline.shp')
```
```{r}
minneapolis_centerline.data = fortify(minneapolis_centerline)
head(minneapolis_centerline.data)
```
```{r}
ggplot(data=minneapolis_centerline.data, aes(x=long, y=lat)) +
  geom_polygon(aes(group=group), fill='#3b3a3a', color='#707070') + coord_quickmap() +
  geom_point(x=44.9749, y=-93.2373, shape = 8, size=2, fill='#fcf919', color='#000000') + theme_map() + 
  geom_point(
    data = bike_racks, 
    aes(x=longitude, y=latitude, fill=Condition),
    shape = 21, 
    size = 2,
    alpha = 0.35
  ) +
  labs(
    title = "Bike Racks in Minneapolis",
    subtitle = 'Focused onto the University of Minnesota',
    caption = 'Minneapolis Open Data (2022)',
    fill = 'Bike Rack Condition'
  ) + theme(
    plot.title = element_text(face = 'bold',size=18),
    plot.subtitle = element_text(size=12),
    plot.caption = element_text(size=8, face='italic',color='grey70', hjust=0),
    legend.title = element_text(size=8, face = 'bold.italic'),
    legend.position = c(0.85,0.07),
  )  + coord_cartesian(xlim = c(-93.22,-93.26), ylim = c(44.965,44.985))
```

